from PyQt5.QtWidgets import QApplication, QLabel, QWidget, QPushButton, QVBoxLayout
app = QApplication([])
window = QWidget()
layout = QVBoxLayout()
layout.addWidget(QLabel('Test app'))
layout.addWidget(QPushButton('Button1'))
layout.addWidget(QPushButton('Button2'))
window.setLayout(layout)
window.show()
app.exec_()
