# Generated by Django 3.0.4 on 2020-03-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200330_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choise',
            new_name='choice_text',
        ),
    ]
